# F:/Python Apps/LekkerBill_Django_Clean/nixpacks.toml

[phases.setup]
# Add system packages needed by weasyprint for PDF generation
# Also include Python itself to ensure it's available in the build environment.
nixPkgs = ["pkgs.python312", "pkgs.cairo", "pkgs.pango", "pkgs.gdk-pixbuf"]