# F:/Python Apps/LekkerBill_Django_Clean/nixpacks.toml

[phases.build]
# Take full, explicit control of the build process.
# First, update apt and install system dependencies for weasyprint.
# Then, after the system is ready, install the python packages.
# This explicit order prevents the automatic 'migrate' from running too early
# and ensures the required libraries are present.
cmds = [
    "apt-get update && apt-get install -y --no-install-recommends libcairo2 libpango-1.0-0 libgdk-pixbuf2.0-0 && rm -rf /var/lib/apt/lists/*",
    "pip install -r requirements.txt"
]