# F:/Python Apps/LekkerBill_Django_Clean/nixpacks.toml

[phases.setup]
# Use apt to install packages on the underlying Debian system.
# This is the most direct and reliable way to add the dependencies for weasyprint.
aptPkgs = [
    "libcairo2", "libpango-1.0-0", "libgdk-pixbuf2.0-0"
]