# Generated by Django 5.2.3

import uuid
from django.db import migrations, models

# This function will be run to populate the UUIDs for existing Invoice rows
def gen_invoice_uuid(apps, schema_editor):
    Invoice = apps.get_model('invoices', 'Invoice')
    for row in Invoice.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        # This now correctly points to the previous migration
        ('invoices', '0002_customer_created_at_customer_updated_at_and_more'),
    ]

    operations = [
        # 1. Add the field, but allow it to be null temporarily
        migrations.AddField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        # 2. Run our Python function to populate the null fields with unique UUIDs
        migrations.RunPython(gen_invoice_uuid, reverse_code=migrations.RunPython.noop),
        # 3. Alter the field to make it non-nullable and behave as we originally wanted
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]