# Generated by Django 5.2.3 on 2025-08-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='invoice_next_number',
            field=models.IntegerField(default=1, help_text='The next number to be used for a new invoice.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='invoice_prefix',
            field=models.CharField(default='INV-', help_text='The prefix for your invoice numbers (e.g., INV-).', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='quote_next_number',
            field=models.IntegerField(default=1, help_text='The next number to be used for a new quote.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='quote_prefix',
            field=models.CharField(default='QTE-', help_text='The prefix for your quote numbers (e.g., QTE-).', max_length=10),
        ),
    ]
