# Generated by Django 5.2.3 on 2025-07-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoice_paid_invoice_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='subscription',
            name='payfast_token',
            field=models.CharField(blank=True, help_text='Unique token for the recurring billing agreement from PayFast.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', help_text='Status of the subscription.', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_end_date',
            field=models.DateField(blank=True, help_text='The date when the current subscription period ends.', null=True),
        ),
    ]
