# Generated by Django 5.2.3

import uuid
from django.db import migrations, models

# This function will be run to populate the UUIDs for existing Quote rows
def gen_quote_uuid(apps, schema_editor):
    Quote = apps.get_model('invoices', 'Quote')
    for row in Quote.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        # This now correctly points to the previous migration
        ('invoices', '0006_invoice_invoice_number_profile_account_holder_name_and_more'),
    ]

    operations = [
        # 1. Add the field, but allow it to be null temporarily
        migrations.AddField(
            model_name='quote',
            name='uuid',
            field=models.UUIDField(null=True, unique=True),
        ),
        # 2. Run our Python function to populate the null fields with unique UUIDs
        migrations.RunPython(gen_quote_uuid, reverse_code=migrations.RunPython.noop),
        # 3. Alter the field to make it non-nullable and behave as we originally wanted
        migrations.AlterField(
            model_name='quote',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]