# Generated by Django 5.2.3 on 2025-07-17 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0002_customer_created_at_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayFastITN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_post_data', models.TextField(blank=True)),
                ('payment_status', models.CharField(blank=True, max_length=20)),
                ('amount_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('result', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.profile')),
            ],
        ),
    ]
