# Generated by Django 5.2.3 on 2025-08-01 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayFastITN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_post_data', models.TextField()),
                ('payment_status', models.CharField(blank=True, max_length=255)),
                ('amount_gross', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('m_payment_id', models.CharField(blank=True, help_text="Merchant's internal payment ID (e.g., Subscription ID)", max_length=255, null=True)),
                ('token', models.CharField(blank=True, help_text="PayFast's unique token for a recurring subscription", max_length=255, null=True)),
                ('result', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.profile')),
            ],
            options={
                'verbose_name': 'PayFast ITN Log',
                'verbose_name_plural': 'PayFast ITN Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
