# Generated by Django 5.2.3 on 2025-07-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payfast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payfastitn',
            options={'ordering': ['-created_at'], 'verbose_name': 'PayFast ITN Log', 'verbose_name_plural': 'PayFast ITN Logs'},
        ),
        migrations.AddField(
            model_name='payfastitn',
            name='m_payment_id',
            field=models.CharField(blank=True, help_text="Merchant's internal payment ID (e.g., Subscription ID)", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payfastitn',
            name='token',
            field=models.CharField(blank=True, help_text="PayFast's unique token for a recurring subscription", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payfastitn',
            name='amount_gross',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payfastitn',
            name='payment_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payfastitn',
            name='raw_post_data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='payfastitn',
            name='result',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
